Extensions/TextEntryVirtualKeyboard-header.json
Extensions/TextEntryVirtualKeyboard.json
extensions-registry.json

Made by @Bouh in https://github.com/4ian/GDevelop-extensions/issues/11
Let's continue the discussion here :)
I've cleaned the extension (double check though that it's still working, because I found something fishy in the closeKeyboardById function => it was refering to the eventsFunctionContext not passed as parameter, which must never be done!).
An example was included in https://github.com/4ian/GDevelop-extensions/issues/11
Ideally, I would like to see how to bundle examples and even documentation - to be sure that it's easy to understand, use and maintain these custom behaviors.

Add Mobile virtual keyboard for Text Entry behavior

---

Extensions/FireBullet-header.json
Extensions/FireBullet.json
extensions-registry.json

Added an onCreated function to reset the timer "FireCooldown" of the
Object as soon as it is created.
Without this, the first attempt to shoot creates the timer, but doesn't
shot because "FireCooldown" seconds haven't passed yet.

Fix bullet not firing on first shot

---

Extensions/Swipe.json

Added extensions that include Swipe behavior. This behavior attaches to any object and “handles the swipe event”.
Behavior settings:
- `Time (s)` - duration of the swipe (default value _0.2 s_);
- `Min Length (px)` - the minimum length that the swipe must “pass” (default value _100 px_).
Output values / functions:
- `IsDone` (_Condition_) - swipe done or not;
- `StartPointX`, `StartPointY` (_Expression_) - coordinates of the point where the swipe starts;
- `EndPointX`, `EndPointY` (_Expression_) - coordinates of the swipe end point;
- `Length` (_Expression_) - the length of the swipe;
- `DirectionX`, `DirectionY` (_Expression_) - values of the swipe direction vector;
- `DirectionNormX`, `DirectionNormY` (_Expression_) - values of the normalized vector of the swipe direction;
- `Angle` …

Add extension Swipe

---

Extensions/Clipboard-header.json
Extensions/Clipboard.json
extensions-registry.json

Adds support via cordova plugins for mobile clipboard, hide deprecated ReadText expression, and bump to version 1.0.0 as I think it can be considered stable and complete as now that all platforms are supported, changes to the API are unlikely. 
Tested on my FairPhone 3.

Add mobile support to clipboard extension

---

Extensions/FlexBox-header.json
Extensions/FlexBox.json
extensions-registry.json

Adds a behavior to use flexbox layout inside GDevelop.  
[Example project](https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/609ec3db127ab987a25fe16e/e53fd9e0bd2b32b399d3948a7420c831/layout.zip).

Add FlexBox extension

---

Extensions/ToggleSwitch.json

This uses the new "Clear" action of the ShapePainter indroduced in GDevelop 5.0.0-beta115.
It avoid to rebuild the shapes at every frame.
https://www.dropbox.com/s/pwwtqds56e5048f/MarchingSquares.zip?dl=1

[Switch] Draw only when needed.

---

Extensions/DraggableSliderControl.json

This uses the new "Clear" action of the ShapePainter indroduced in GDevelop 5.0.0-beta115.
It avoid to rebuild the shapes at every frame.
An example, to test: https://www.dropbox.com/s/pwwtqds56e5048f/MarchingSquares.zip?dl=1
and its build: https://games.gdevelop-app.com/game-b6f7ae43-151b-4cd1-95fe-fc30cadcb56c/index.html

[Slider] Draw only when needed.

---

Extensions/CancellableDraggable.json
extensions-registry.json

This behavior add an action to tween back the object to it's original position.
It requires Tween and Draggable behaviors.
There is not many events but I think it can often be useful when using the Draggable behavior.
Example
* a card games: https://www.dropbox.com/s/0v113sqm2vi9kds/Klondike.zip?dl=1
Press "Back" to skip the animation.

Cancellable Draggable behavior with tweens

---

Extensions/SpriteMasking.json

Changes
* Add an action to mask with a shape painter
* Make the the masked object parameter any object type instead of only Sprite
* Reword the description according to these changes
The JS code is an exact copy of the other mask action.
* Example : paint a textured shape with the mouse.
https://www.dropbox.com/s/pwwtqds56e5048f/MarchingSquares.zip?dl=1

[Mask] Make it explicit that a shape painters can be used as a mask on any objects

---

Extensions/ThreeDFlip.json

Changes
* The speed property is replaced by a duration parameter to use it like Tweens.
This is a breaking change so the version is incremented to 1.0.0
* The flipping uses a cosinus to make it more realistic.
* A flipping animation can be revert at any time.
* An example of animation on cards (position tween + flipping)
https://www.dropbox.com/s/0v113sqm2vi9kds/Klondike.zip?dl=1
* A comparison with the previous version on the original example (the flip duration is long to let see what happens)
https://www.dropbox.com/s/3xh24b5bnmbgi4d/3D%20Flip%20extension%20Example.zip?dl=1
Extension thread: https://github.com/GDevelopApp/GDevelop-extensions/issues/184

[Flip3D] Duration instead of speed, trigo, revert at any time.

---

Extensions/DraggableSliderControl.json
extensions-registry.json

This add 3 properties (it doesn't break compatibility)
* Minimum value (0 by default)
* Maximum value (1 by default)
* Tick spacing (0 = none by default)
Properties, actions and parameters name now better follow recommendations.
User input handling has been moved from post to pre (it was already separated from drawing in the previous update)
* Fog of war example: https://www.dropbox.com/s/jt7b2qmp5di33ny/marching-square-fog-of-war.zip?dl=1

[Slider] Value range and tick spacing

---

Extensions/LinkTools.json

Objects could freeze at node because of the distance check (square distance against distance).
See the tactical relative example update for reproducing steps:
https://github.com/GDevelopApp/GDevelop-examples/pull/124

[LinkTools] Fix pathfinding movement

---

Extensions/FlashTransitionPainter.json

Change PARAM4 by PARAM5 (which refers to direction) in the sentence of the action PaintEffect

correction in sentence of the extension FlashTransitionPainter

---

Extensions/ShakeObject.json

Testing can be done here (source files available):
https://victrisgames.itch.io/gdevelop-camera-shake-example
Thank you to everyone who reported this issue!

Fixed floating-point rounding errors that caused drifting on ShakeObject

---

Extensions/CameraShake.json

Testing can be done here (source files available):
https://victrisgames.itch.io/gdevelop-camera-shake-example
Thank you to everyone who reported this issue!

Fixed floating-point rounding errors that caused drifting on CameraShake

---

Extensions/InAppPurchase.json

* This allows to sell items or premium features in games published on the stores on Android (Google Play) and iOS (App Store).
* This extension is still **experimental** - and more complex than other things to set up. Be sure to read the [explanation page on the wiki](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/in-app-purchase).
Thanks @arthuro555 for this extension! :)

Add In-App Purchase extension

---

Extensions/StayOnScreen.json

Tested in fullscreen and windowed with the hitbox debugger, it's works fine now.

[Stay On Screen] Fix max X and max Y of the object position

---

Extensions/BehaviorRemapper.json
Extensions/KeyRemapper.json

A simple extension that aims to simplify the process of changing control schemes. By making it possible to change the control scheme in a single action. 
1.  Attach top-down or platform character behavior to an object.
2.  Use the corresponding action to set the controls of the object.

Create key remapper extension

---

Extensions/ExtendedMath.json

* Fix a bug in the "Map" function `* (max2 - min1)`
* Move the multiplication first because the ranges will probably be wider than 1 and it's better to "divide" a rounding error rather than "multiplying" it.
* Remove keywords that were not relevant.
* New
```JavaScript
eventsFunctionContext.returnValue = (n - min1) * (max2 - min2) / (max1 - min1) + min2;
```
* Old
```JavaScript
eventsFunctionContext.returnValue = (n - min1) / (max1 - min1) * (max2 - min1) + min2;
```

[ExtendedMath] Fix the "Map" function.

---

Extensions/RenderToSprite.json
scripts/lib/ExtensionsValidatorExceptions.js

- Fixes bug that created a new RenderTexture on each call eventually crashing WebGL when used every frame
- Fixes sprites not keeping their original height and width when rendering a scene or layer into them
- Fixes culling not being updated before rendering

Update render to sprite extension

---

Extensions/Gamepads.json

I predict that the gamepad extension is going to be one of the most used (and it will eventually be included by default), so I thought I would give it some love.
To do this, I changed almost all string parameters to use a list. 
The one exception was "C_Controller_type".
I think this function compares the given string parameter "controllerType" with the "gamepad.id" string provided by the gamepad device.  However, I don't understand how this is done using this line:
```
eventsFunctionContext.returnValue = gamepad ? gamepad.id.toUpperCase().indexOf(controllerType) !== -1 : false;
```
Can someone confirm that this function should not use a list of strings?

Updated Gamepad parameters to use a list of strings

---

Extensions/DraggableSliderControl.json

- Added new vertical slider behavior
- Updated horizontal slider to use color picker
- Updated horizontal slider to use a list of strings (Rectangle/Circle)
- Added link to test extension:
https://victrisgames.itch.io/draggable-slider-control-extension
- Fix logic on setting Inactive Track color
- Decide if the horizontal version should be renamed with the word "Horizontal"
https://user-images.githubusercontent.com/8879811/146629931-5a50f539-8f8f-401a-bcf9-34f7e03d9fa0.mp4

Added vertical slider

---

Extensions/PopUp.json

Extension to open pop ups.
The extension uses the methods given by javascript (`alert()`, `confirm()`, `prompt()`)
Alert the user which the user can respond with `OK`
Ask confirmation of the user. The user can respond with `OK` or `Cancel`
Gives a pop-up in which the user can enter text
**⚠ Prompt only works in a browser**
https://games.gdevelop-app.com/game-9d2c6973-1a11-49f8-9b38-70eb7a35c5da/index.html
[Prompt.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7696654/Prompt.zip)

Add pop-up extension

---

Extensions/SmoothCamera.json

The camera follows an object according to:
- a frame rate independent speed to make the scrolling from smooth to strong
- a follow-free zone to avoid scrolling on small movements
- an offset to see further in one direction
- position forecasting and delay to simulate a cameraman response time
- an extra delay and catch-up speed to give an impression of speed (like a spin dash)
- a platformer dedicated behavior to stabilize the camera for jumps
4 camera settings (press Return) and a catch up like the spin dash (the object need to be fixed before the dash)
- Stabilized jump exponential following
- Exponential following
- Linear following (Sonic like)
- Shoulder camera (not a great idea for platformers)
* Project: https://www.dropbox.com/s/08d29yjf5kf3817/AdvancedJumpAirAndWallJumpExample_D8H …

Add the SmoothCamera extension to follow an object.

---

Extensions/CloneCamera.json
Extensions/CopyCameraSettings.json

Useful when multiple layers need to use the same camera values.
How to use:
- Run the "Clone camera settings" action after all other camera actions have been performed
Tips:
- Do not use on layers that implement a parallax effect
https://liluo.io/games/1e988edc-a480-42c9-a6b4-b6454fb2454a
[CloneCamera.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8393393/CloneCamera.zip)
https://user-images.githubusercontent.com/8879811/161161165-8342e1d3-cf29-46ee-b69e-71011d29aa7b.mp4

New extension: CloneCamera - Copy the camera settings of a layer and apply them to another layer

---

Extensions/PlatformerTrajectory.json
scripts/lib/ExtensionsValidatorExceptions.js

Add a behavior (PlatformerEvaluator) that allows to
* Configure the height of a jump by automatically choosing the right jump speed.
* Know when to jump to reach a platform (can be useful for IA).
* Draw jump trajectories to check a level design.
I stated to write a documentation here:
https://github.com/4ian/GDevelop/tree/master/Extensions/PlatformBehavior#jump-trajectory
I used JavaScript because I think it might be useful to have some parts in GDevelop directly.
It needs GDevelop 125 to be more precise.
* Build: https://d8h.itch.io/platformer-jump-evaluator
* Project: https://www.dropbox.com/s/9mhv6vtxc0w3708/platformer-jump-evaluator.zip?dl=1

[PlatformerTrajectory] Add a behavior to evaluate jump trajectories.

---

Extensions/CursorMovement.json

* The cursor position is saved in `onScenePostEvents` instead of the condition itself.
* The condition won't work if the default layer is moving.
This might need some JavaScript to get the cursor position in the window referential so I prefer to do it in another PR to merge this quickly.
* https://www.dropbox.com/s/wgwkzboyinbu3vi/StillCursorTest.zip?dl=1
Thank you Ash for reporting the issue.

[CursorMovement] Fix conditions were always returning true when called a 2nd time.

---

Extensions/PixelPerfectMovement.json

Fix: top-down characters moving on a grid no longer go side way after colliding with an obstacle.
* PR: https://github.com/GDevelopApp/GDevelop-examples/pull/312
* Project: https://www.dropbox.com/s/57hf3rnozd5em5a/top-down-grid-movement.zip?dl=0
* Try it: https://liluo.io/instant-builds/52f4e501-aa73-4d9c-a5e8-6e701a200abc

[PixelPerfectMovement] Fix: top-down characters collision

---

extensions/reviewed/DraggablePhysics.json

- Change Kinematic mode to Dynamic mode to prevent crash
- Set "left" mouse button as default
https://liluo.io/games/02910630-65f7-4dc4-aa26-3f262bc888ec
This object is assigned kinematic, but the extension forces it to be dynamic.
[DraggableNonDynamic_BugFix.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9128505/DraggableNonDynamic_BugFix.zip)

Update DraggablePhysics.json to force Kinematic to Dynamic

---

extensions/reviewed/SmoothCamera.json

This add an action to choose when the camera following must be applied to avoid a delay.
Note for reviewers: the change is only in the function:
- onPreEvents: its call DoMoveCameraCloser
- MoveCameraCloser: it calls DoMoveCameraCloser
- DoMoveCameraCloser: contains what was in onPreEvents
The delay does some kind of glitch.
* Camera following in the life-cycle function: 1 frame delay
https://games.gdevelop-app.com/game-c29f6b40-81cd-422f-b683-372675135e66/index.html
* Camera following after the player movement though an action: no delay
https://games.gdevelop-app.com/game-5d60504f-534f-4194-b9d0-b0b3649c3fbc/index.html  
Example:
* https://github.com/GDevelopApp/GDevelop-examples/pull/364

[SmootCamera] Add an action to fix the 1-frame delay.

---

extensions/reviewed/SmoothCamera.json

This is just an automatic refactor to have a root variable for the extension and avoid to pollute the debugger.
- Project: https://www.dropbox.com/s/08d29yjf5kf3817/AdvancedJumpAirAndWallJumpExample_D8H-1.zip?dl=1

[SmoothCamera] Use a parent variable for the extension.

---

Extensions/EdgeScrollCamera.json

Edge scroll camera allows the player to move around the scene simply by moving the cursor near the edge they want the camera to move towards.  This is common in RTS games, but it can be useful for many things.
How to use:
- Run the action "Enable (or disable) edge camera scrolling" at the beginning of scene
- Run the action "Configure edge camera scrolling" at the beginning of scene
Tips:
- Variable speed makes the camera scroll faster the closer the cursor gets to the edge of screen
- Use the action "Enable (or disable) edge camera scrolling" to turn the scrolling ON or OFF
- Use the action "Enforce camera boundaries" to restrict what the player can see
- Use the extension "Copy camera settings" if you want multiple layers to move …

New extension: EdgeScrollCamera

---

extensions/reviewed/CameraImpulse.json

* It can be used to simulate earthquakes or impacts.
It also uses:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/387
Press `I` to start an impulsion and `S` to shake.
I didn't find any conflict between the impulse and the scrolling or the screen shake.
- Project: https://www.dropbox.com/s/spvas50648blctc/platformer-with-tilemap-shake.zip?dl=1
- Build: https://games.gdevelop-app.com/game-881fc8e5-272e-460a-8d72-7d01baca255d/index.html

Add the CameraImpulse extension.

---

extensions/community/Geolocation.json
extensions/community/ObjectPickingTools.json
extensions/community/References.json
scripts/generate-extensions-registry.js
scripts/lib/ExtensionsValidatorExceptions.js

Adds a few community extension I made some time ago and forgot to submit.
Geolocation - Allows to locate a player using the Web Geolocation API
References - Allows to make a scene variable a reference to some other variable (necessary for some algorithms and data structures, albeit rather advanced hence why it is an extension rather than a core feature)
ObjectPickingTools - An extension requested by Silver-Streak sometime ago to help with object picking by allowing to pick objects of an object list one-by-one, unpick them, pick the one with highest/lowest z-Order...
Also adds a small fix to the build code for the auto-fixing feature.

[New community extensions] Geolocation, References and ObjectPickingTools

---

extensions/reviewed/AutoTyping.json
extensions/reviewed/CursorType.json
extensions/reviewed/ObjectSpawner.json

It can be reviewed directly with the diff.

[AutoTyping, CursorType, ObjectSpaner] Remove useless "Change" prefix in actions full name

---

extensions/reviewed/CameraShake.json
scripts/lib/ExtensionsValidatorExceptions.js

* Embed the Noise extension for a more realistic shake (especially at low frequency)
* Configuration per layer
* Linear easing
* Fix conflicts with camera movements.
Try it:
* Project: https://www.dropbox.com/s/nai88cdnjg76ynm/ScreenShakeExamples.zip?dl=1
* Build: https://liluo.io/instant-builds/e0257129-0d90-46f3-b029-42c12f8b9854
It also uses:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/529
Press `I` to start an impulsion and `S` to shake.
I didn't find any conflict between the impulse and the scrolling or the screen shake.
- Project: https://www.dropbox.com/s/spvas50648blctc/platformer-with-tilemap-shake.zip?dl=1
- Build: https://games.gdevelop-app.com/game-881fc8e5-272e-460a-8d72-7d01baca255d/index.html
It uses a JavaScript event but it's just a copy-paste of the Noise …

[ScreenShaking] Multi-layer, noise based shaking, scrolling-compatible.

---

extensions/reviewed/ToggleSwitch.json

It can be reviewed directly with the diff.

[ToogleSwitch] Remove useless "Change" prefix in actions full name.

---

extensions/reviewed/AutoTyping.json

- Added an action to skip to end of text
- Added a condition to check when a new character was displayed (to trigger sound effects)
- Added an expression to return the character that was just displayed (to perform conditional logic)
- Before this change, it would always show the first character, even if you paused it at the beginning of the scene.
https://liluo.io/instant-builds/b94cd280-c4a7-4262-bb14-072c8a9c27b3
[AutoTyping.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9557419/AutoTyping.zip)
https://user-images.githubusercontent.com/8879811/189468539-d620bce0-0dc7-40c8-88a5-e5a8e36a5625.mp4

AutoTyping: Added multiple functions and a minor fix

---

extensions/reviewed/InAppPurchase.json

Following 2 raised problems on the forum: 
- https://forum.gdevelop.io/t/inapppurchase-outdated/41962
- https://forum.gdevelop.io/t/inapppurchase-unsupported-version-of-play-billing/41926/16
I believe we can safely update the cordova plugin to handle the Play Billing v4
https://github.com/j3k0/cordova-plugin-purchase/releases

Upgrade Cordova IAP to 11.0.0

---

extensions/reviewed/Record.json

- Fix "event" parameter not used in `dataavailable` event.
- Explain that "Stop" will only give the data available to save at the next frame.

Fix Record extension not working on a web game

---

extensions/reviewed/MarchingSquares.json

It's a very small change in the JS that I forgot to do in the previous update.
It also add examples links directly in the extension long description.
Note to the reviewer:
- The example contains the fixed version
- Launch a preview and it should work
- Downgrade to the current version
- Launch a preview, there should be exception every frame.
https://www.dropbox.com/s/u2juv7b7cypz5uu/LiquidMarchingSquareFix.zip?dl=1

[Marching Squares] Fix a preview crash when the "Must only draw what is on the screen" property was checked.

---

extensions/reviewed/CameraShake.json

The example from Tristan was made for a previous update. It allows to see that it still works with the fix.
[CameraShakeExample.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9639664/CameraShakeExample.zip)

[CameraShake] Fix compatibility with the extension version prior to 3.0.0

---

extensions/community/LoadImageFromURL.json

Adds an extension to load an image from a URL into a sprite or an image resource.
Example file: [load-from-url.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9717163/load-from-url.zip)

Add LoadImageFromURL extension

---

extensions/community/JSONResourceLoader.json

Adds an extension to load JSON resources into variables.
Example file: [load-from-url.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9717163/load-from-url.zip)

Add JSON Resource loading extension

---

extensions/reviewed/MultitouchJoystick.json

- Fix the angle range on the "UP" condition
- Require joystick to be pushed from the center
- Change the wording from "Activate" to "Animate" since it must run every frame, not a one-time event
I built a better game to test these conditions:
4-way test
https://liluo.io/instant-builds/f8059352-1530-482c-82ca-ed427817d372
8-way test
https://liluo.io/instant-builds/8f33a138-221a-40e7-95bb-8fec365c5265
[Multitouch-fixes.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9915487/Multitouch-fixes.zip)
https://user-images.githubusercontent.com/8879811/199383607-76332db0-0dee-4171-9759-c068cb444318.mp4

[MultitouchJoystick] [Reviewed] Minor fixes (v1.1.1)

---

extensions/reviewed/MultitouchJoystick.json

- Add properties on the stick and button behaviors to identify a controller.
- Add free condition and expression for these controllers (a bit like the gamepad extension).
- Add a behavior to map a controller to a platformer character.
- https://github.com/GDevelopApp/GDevelop-examples/pull/415

[Reviewed] [Multitouch joystick] Add a multitouch controller mapper behavior for platformer characters.

---

extensions/reviewed/ShadowClones.json

This is based on PR #477, with a small change to use Boolean variables.

[ShadowClones] [Reviewed] Added the ability to match horizontal and vertical flip of a sprite (thanks @fuzzystudios)

---

extensions/community/PanelSpriteSlider.json

[Community] [Slider] Fix value changes when moving several thumbs.

---

extensions/community/SpriteToggleSwitch.json
extensions/reviewed/PanelSpriteButton.json

[Reviewed] [Button] Simpler FSM

---

extensions/reviewed/FollowObjectsWithCamera.json

Changed the calculations to use AABB instead of trying to estimate the proper width/height.
This problem was noticeable with very long objects, but now it works perfectly!  (Try dragging the long blue objects)
https://liluo.io/games/9afd7a87-e2ac-4598-b387-713f6bbee373
[MoveAndZoomCameraToKeepObjectsOnScreen.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10334026/MoveAndZoomCameraToKeepObjectsOnScreen.zip)
https://user-images.githubusercontent.com/8879811/210291535-88f7b148-a544-4763-b123-2dd62f0fae1e.mp4

[Follow multiple objects with camera] [Reviewed] Changed calculations to use AABB (bounding boxes)

---

extensions/reviewed/StayOnScreen.json

- Use the bounding box instead of position and dimensions.
- Add actions to change the margins.
- https://github.com/GDevelopApp/GDevelop-examples/pull/452

[Reviewed] [Stay on screen] Use the bounding box instead of the position and the dimensions

---

extensions/reviewed/Clipboard.json

This adds a new action for the clipboard extension that is an async action. 
Relies on https://github.com/4ian/GDevelop/pull/4819
Additionally:
- Changed the parameter from a string to an actual variable field on the new action
- Privated the old one to discourage further use
- Added `[DEPRECATED]` in front of the original clipboard read expression that did not work cross-platform

Make the clipboard extension ✨true async✨

---

extensions/reviewed/PanelSpriteSlider.json

[Reviewed] [Slider] Add a condition to check when the slider is dragged

---

extensions/reviewed/Health.json

* Adds back the `SetHealth` action
* Add condition on health and shield values
* https://github.com/GDevelopApp/GDevelop-examples/pull/464

[Reviewed] [Health] Fix the compatibility with old versions of the extension

---

extensions/reviewed/PanelSpriteSlider.json

[Slider] Fix slider disappearance when the minimum value is set to 1.

---

extensions/reviewed/AuthorizedPlatformsValidation.json
extensions/reviewed/ValidateExecutionContext.json

This is a small extension made to check where a game exported to web is executed to insure it is not being published and played on an unauthorized platform.
Some platforms scraps websites such as itch.io (and gd.games) in the search to republish small but relatively popular games on their website without the owner's content and then display ads on the page to make profit out of a game they did not even have the right to publish !
This extension allows for gamedevs to define with events which platforms are allowed and can use the "The game is running on a valid context" conditon to act accordingly for example, displaying a warning message or block the game entirely.

Extension proposition : Authorized Platform Validation

---

extensions/reviewed/PanelSpriteButton.json

- Nothing change for users
- The toogle switch uses the reset function
https://github.com/GDevelopApp/GDevelop-extensions/pull/804
- https://github.com/GDevelopApp/GDevelop-examples/pull/488

[Button] Add a private reset function for other extensions using the FSM

---

extensions/reviewed/SpriteToggleSwitch.json

- Add "has just been checked" and  "has just been unchecked" conditions.
- Reset the button state when the "SetChecked" action is used to allow a sort of dragging for the toolbar of the example. It avoid a touch to end when the button has changed of state from events because the user intent would be inverted.
- https://github.com/GDevelopApp/GDevelop-examples/pull/488

[Toggle switch] Add a "has just been checked" condition to allow radio button group

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md
extensions/community/PauseFocusLost.json
scripts/check-single-extension.js
scripts/extract-extension.js
scripts/lib/ExtensionNameValidator.js
scripts/lib/ExtensionsValidatorExceptions.js

Updated
- Add black line
- Remove trailing whitespace
- Emphasis style consistently
- Typo
- workinng -> working

Clean markdown files and fix typos

---

extensions/reviewed/ButtonStates.json

Provides conditions that detect how the player is interacting with an object.
Allows any object to be used like a button.
Note: This is the same behavior used for Panel Sprite Buttons, but this behavior can be used on any object.
https://gdevelop.io/game-example/buttons
https://gd.games/victrisgames/button-states

[Reviewed] [Button states] Provides button states including idle, hovered, pressed, and clicked.

---

extensions/reviewed/FireBullet.json

* Actions can now be applied to the bullet created by the extension.
* https://github.com/GDevelopApp/GDevelop-examples/pull/523

[Reviewed] [Fire bullet] Fix bullets picking

---

extensions/reviewed/DraggablePhysics.json

Default dragging requires the cursor to be over an object. This is not great for fabrics of small objects, because there is a lot of space that will not trigger a drag to start.  This change adds a new action to manually start dragging, so game creators can choose when and which objects to grab.
To enable this logic, I added a new option to the Mouse Button property: "None (disable automatic dragging)".
Do you like this implementation, or should I make a separate property, such as: "Enable automatic dragging"?
https://gd.games/victrisgames/building-monsters

Add "Start dragging object" to enable custom picking of object to be dragged

---

extensions/reviewed/MousePointerLock.json

On devices with a touchpad and a usb mouse connected, sometimes the mouse acceleration does not match on both devices. To prevent the mouse from jumping around, I disabled the default system acceleration
```js
canvas.requestPointerLock({
unadjustedMovement: true
});
```
Example: https://youtu.be/AdXtAb_7_gg
Reference: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

fix: mouse acceleration on laptop

---

extensions/reviewed/FPS.json

- Uses a sliding window to show exactly the number of frames in the previous second
- Backwards compatible with the previous extension
https://gd.games/victrisgames/load-testing
https://github.com/GDevelopApp/GDevelop-examples/pull/544
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/fb5d5953-b3fe-48f2-887b-047cbada839d

[FPS] Update: Provide more accurate values for frames per second

---

extensions/reviewed/Flash.json
scripts/lib/ExtensionsValidatorExceptions.js

- Flash color tint
- Flash effect
- Flash opacity (fade)
- When "Flash object" action is used during an pre-existing flash, simply extend the duration of the flashing 
- Previously, it always started with "hide object", potentially causing the object to be hidden too much
https://gd.games/victrisgames/flash-object-extension-example
https://github.com/GDevelopApp/GDevelop-examples/pull/554
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/401d5d73-c13f-4e94-96be-05afb6ff7b55

[Flash object] Add ability to flash color tint, object effect, and opacity (fade)

---

extensions/community/SelectionTools.json

The extension provides functionality to draw different types of selections in order to select object instances present on the scene. 
- Create a shape painter object. It would be used to draw the selection on the screen.
- Add the `Setup selection tools` action to an event.
- Add the setup action for the required selection. Choose from: `Set rectangular selection`, `Set polygonal selection`, and `Set lasso selection`.
---
- Project: [SelectionTools Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12333279/SelectionTools.Example.zip)
- Build: https://gd.games/instant-builds/008aa4fb-a228-4eeb-9543-e4004d96d04b

New extension SelectionTools.

---

extensions/reviewed/MousePointerLock.json

Listen `pointermove` instead of `mousemove` to make it work on with touch events too.

[Reviewed] [Mouse pointer lock] Add handling of touches

---

extensions/reviewed/InAppPurchase.json

tested with example: https://github.com/GDevelopApp/GDevelop-examples/pull/574
Mainly followed https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13 and API of functions for upgrade.

Upgrade in app purchase

---

.github/workflows/auto-pr.yml
scripts/check-single-extension.js
scripts/lib/ExtensionValidator.js
scripts/lib/rules/JavascriptDisallowedProperties.js
scripts/lib/rules/rule.d.ts

Adds a concept of "Preliminary checks" to the extension checker, where some rules can be ignored. By submitting an extension through an issue, the non-preliminary checks will no longer be ran, but will still be ran by the CI etc. and block a merge until a reviewer takes a look at it.
The rule "Disallowed JS properties" has been added as the single non-preliminary check, as to allow creating the PR for the reviewer to take a look at the disallowed properties in use and add them to the ignore list if appropriate.

Ignore JS disallowed properties in issues

---

extensions/community/NavMeshPathfinding.json
extensions/community/TopDownMovementAnimator.json

- There were spaces after the object name and after `::` in some expressions. It better handled by new version of GDevelop and the extension used a negation were it shouldn't to fall on it feet.

[Community] [Movement animator] Fix the animation changes with GDevelop 5.2.172+

---

extensions/reviewed/CancellableDraggable.json

- https://github.com/GDevelopApp/GDevelop-examples/pull/599

[Reviewed] [Cancellable draggable] Use seconds instead of milliseconds

---

extensions/reviewed/ObjectSpawner.json

Offsets were originally designed to enable random positions, but this new implementation is much cleaner. The offset method can still be used by adding a value to the position of objects as a subevent to the "Periodically spawn objects".  This was not possible before GDevelop started picking objects created by extensions.
Playable game:
https://gd.games/instant-builds/cbf53f3e-449a-45e2-b7c1-011f257c7343
Project file:
[ObjectSpawnerRandomPositions.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/13540079/ObjectSpawnerRandomPositions.zip)

[Reviewed] [Object Spawner] Added "Random Position" checkbox and deprecated "Offset" properties

---

extensions/reviewed/MousePointerLock.json

Avoid errors when running the "Request Pointer Lock" and "Exit pointer lock" actions in Safari on iOS.

[Reviewed] [Mouse pointer lock] Avoid errors in Safari on iOS.

---

extensions/reviewed/RepeatEveryXSeconds.json

- Deprecate the properties and use parameters instead to allow to use several object timers
- Add scene/object in names to tell conditions apart in search results
- Remove usages of "trigger once" as it has unexpected result in functions
- Add an expression and condition to check the number of repetition done
- Add an action to reset the repetition counter and delete the timer
- Some wording
- https://editor.gdevelop.io?project=https://raw.githubusercontent.com/D8H/GDevelop-examples/repeat/examples/TestRepeat/TestRepeat.json

[Reviewed] [Repeat every X seconds] Allow to use several object timers

---

extensions/reviewed/FlashTransitionPainter.json

- [Transition.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/15051358/Transition.zip)
- Fix the animation for zoomed layers
- Always keep the last frame when `"Forwoard"` is chosen
- Simplify the events
- Add a property for the smoothing radius
- Use the shape painter color and opacity instead of the parameters
- Use easing
- Make 3 actions:
- Fade in
- Fade out
- Fade in and out
- with 2 durations and 2 easing and a pause

[Reviewed] [Transition] Fix the animation for zoomed layers

---

extensions/reviewed/BoidsMovement.json

Should also fix potential problems with "avoid object" action by setting the correct TrajectorySpeed.

[Reviewed] [Boids Movement] Fix typo of VelocityX and VelocityY being swapped

---

extensions/community/PointAndOrbit.json

- Add the ability to point towards an angle (useful for gamepads)
- Converted events to use the new method to reference parameters directly
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/91a5005d-15f2-4f0a-9456-46bec9514389

[Community] [Point and Orbit] Add the ability to point towards an angle (useful for gamepads)

---

extensions/reviewed/ThirdPersonCamera.json

- It allows to keep the player near the bottom of the screen or a bit on the side like in some 3rd person shooters.
- https://github.com/GDevelopApp/GDevelop-examples/pull/677

[3rd person camera] Fix the offset to rotate with the camera.

---

extensions/reviewed/Turret.json

- Use the new syntax for properties
- Remove an unused parameter expression that gave a false positive on variable usage.
- The formulas are overly complicated. Angle expressions could be used instead of low-level trigonometry.

[Reviewed] [Turret] Use the new syntax

---

extensions/reviewed/SpriteMultitouchJoystick.json

- `Force()`, `ForceX()`, `ForceY()` now return 0 when the stick is in the dead zone.
- The force starts at 0 at the end of the dead zone and progressively goes to 1.

[Reviewed] [Multitouch joystick] Fix the dead zone for `Force` expressions

---

extensions/reviewed/CameraImpulse.json
extensions/reviewed/CursorType.json
extensions/reviewed/DoubleClick.json
extensions/reviewed/DragCameraWithPointer.json
extensions/reviewed/EdgeScrollCamera.json
extensions/reviewed/FlashLayer.json
extensions/reviewed/PanelSpriteButton.json
extensions/reviewed/PanelSpriteContinuousBar.json
extensions/reviewed/PanelSpriteSlider.json
extensions/reviewed/SpriteMultitouchJoystick.json
extensions/reviewed/TiledUnitsBar.json
extensions/reviewed/TravelToRandomPositions.json
extensions/reviewed/ValuesOfMultipleObjects.json

* [Flash layer] Simplify the events
* [Double-click] Simplify the events
* [Edge scroll camera] Use extension variables.
* [Camera impulse] Use extension variables.
* [Drag camera] Fix unexpected snapping when the layer is zoomed.
* [Cursor type] Simplify events.
* [Panel sprite button] Use local variables.
* [Multitouch joystick] Use extension variables.
* [Continuous bar] Use local variables.
* [Slider] Use local variables.
* [Units bar] Use local variables.
* [Travel at random] Simplify events.
* [Values of objects] Simplify events.

Use extension variables and simplify events of various extensions

---

extensions/reviewed/Gamepads.json
extensions/reviewed/MousePointerLock.json
extensions/reviewed/SpriteMultitouchJoystick.json
extensions/reviewed/ThirdPersonCamera.json

I forgot to do it here:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1464

Upgrade extension versions

---

extensions/community/NavMeshPathfinding.json

This PR includes fixes and suggestions.
- Fixed an issue where rotation speed was not being applied correctly.
- Added units to properties.
- Set actions to private that change parameters that cannot be changed later, such as "Change the Cell size."
- Added a note to the description of the "Draw navigation mesh" action.
@D8H , What do you think about these changes?
~~
This extension is great in that it works when added to a new tile map object.
It would be better if the navigation mesh could be updated when tiles are changed.
This current solution is not very smart.

[Community] [Navigation mesh pathfinding] Fixed problem with Rotation speed not being applied correctly.

---

extensions/reviewed/TwoChoicesDialogBoxes.json

- Simplify the events
- Hide instructions and properties about button id because users can't know what it means.
- if the feature is ask, it should probably use user-defined button labels. 
- https://github.com/GDevelopApp/GDevelop-examples/pull/746

[Reviewed] [Two choices dialog box] Simplify the events

---

extensions/reviewed/Bounce.json
extensions/reviewed/CurvedMovement.json
extensions/reviewed/FireBullet.json
extensions/reviewed/Flash.json
extensions/reviewed/FlashTransitionPainter.json
extensions/reviewed/Health.json
extensions/reviewed/LinkTools.json
extensions/reviewed/PanelSpriteButton.json
extensions/reviewed/PanelSpriteContinuousBar.json
extensions/reviewed/ShakeObject.json
extensions/reviewed/ShakeObject3D.json
extensions/reviewed/Turret.json
extensions/reviewed/TwoChoicesDialogBoxes.json

- https://github.com/GDevelopApp/GDevelop-examples/pull/766

Migrate some more extensions to properties as variables

---

scripts/generate-extensions-registry.js
scripts/lib/rules/FilledOutDescriptions.js
scripts/types.d.ts

"Database" file goes from 350K to 530K (but it contains behavior/objects registry that are separated by the API, and this is the non gzipped size, so overall it should be ok).

Add behaviors/objects/functions details in ExtensionShortHeader

---

extensions/reviewed/PanelSpriteButton.json
extensions/reviewed/TwoChoicesDialogBoxes.json

It needs a GDevelop release that handles event-based object variants
- https://github.com/4ian/GDevelop/pull/7403
and assets need to be migrated at the same time
Documentation
- https://github.com/GDevelopApp/GDevelop-documentation/pull/296

[Reviewed] [Button] Use anchor behaviors in buttons

---

.github/workflows/commands.yml
scripts/generate-extensions-registry.js
scripts/lib/rules/JavascriptDisallowedProperties.js

It avoids to block extension with JavaScript to be updated:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1755
In a more general manner, it's better to have a missing dot at the end of a sentence rather than a bug in the events. The bot still asks to update the extension again for any broken rule.

Allow to update extensions even if they don't comply all rules
