GDevelopApp/GDevelop-extensions

- Extensions/FireBullet-header.json
- extensions-registry.json
> Remove an white tag in gd search new behavior  cloud tag

- Extensions/SineMovement-header.json
- Extensions/SineMovement.json
The amplitude X and Y can now be negative for inverse the sin wave.
> [Sine extention] Support negative value in amplitude for inverse the sin wave.

- Extensions/ExtendedMath-header.json
- Extensions/ExtendedMath.json
- Extensions/TextEntryVirtualKeyboard-header.json
- extensions-registry.json
Add and close #56 
Your extension @Add00
> Add Extented Math functions and constants by Add00

- Extensions/ExtendedMath-header.json
- Extensions/ExtendedMath.json
- extensions-registry.json
Fix review from https://github.com/4ian/GDevelop-extensions/pull/57
> Fix on Extended math extension

- scripts/update-extensions-registry.js
In reference to double **Camera** tags in the future extension search dialog.
https://github.com/4ian/GDevelop/pull/2140#issuecomment-751380418
> All tags to lower case

- Extensions/BackButton-header.json
- Extensions/BackButton.json
- extensions-registry.json
Adds the possibility to control the back button on mobile and browsers. Doesn't work on electron because electron doesn't have a back button.
> Add BackButton extension

- Extensions/ExtendedVariables-header.json
- Extensions/ExtendedVariables.json
- extensions-registry.json
> Updated extension: Add copy variables to Extended Variables

- Extensions/SnapToGrid-header.json
- Extensions/SnapToGrid.json
- extensions-registry.json
> SnapToGrid: Fix a typo in parameters

- Extensions/Microphone-header.json
- Extensions/MouseHelper-header.json
- Extensions/MouseHelper.json
- extensions-registry.json
Fix descriptions, author, functions name, clean events, version number, remove useless functions
Fix https://github.com/4ian/GDevelop-extensions/issues/143
> Add Mouse Helper

- Extensions/HexagonalGrid-header.json
- Extensions/HexagonalGrid.json
- extensions-registry.json
I thought I couldn't factorized it but I actually did a typo.
Tested with the BimBam example
> HexagonGrid: Factorize the bubble snap

- Extensions/RepeatEveryXSeconds-header.json
- Extensions/RepeatEveryXSeconds.json
- extensions-registry.json
Adds the "Repeat every X seconds" by @VegeTato, an extension that adds convenience abstractions for timers.  
Reviewed and modified to support both objects and scene timers by me.
> Add Repeat every X seconds extension

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/new-extension.md
- .github/workflows/issues.yml
Adding a Github token can be required in settings of this repo.
> Add autoclose for issues with a default template

- Extensions/AutoTyping-header.json
- Extensions/AutoTyping.json
- extensions-registry.json
Ready to merge, it's just a copy paste of a new behaviors adapted for bitmap text object.
It works like other behaviors for text and bbtext.
> AutoTyping add BitmapText support

- Extensions/StarRating-header.json
- Extensions/StarRating.json
- extensions-registry.json
Adds the star rating extension by @Entr0py404 .
I reviewed and tested it.
> Add star rating extension

- Extensions/ExtendedMath.json
Add ToFixed expression.
Review applied.
Close #177
> Update extended math

- Extensions/ArrayTools.json
> Add ArrayTools extension

- Extensions/MagneticEffect.json
- extensions-registry.json
Add Magnetic Effect extension suggested in #195 
Reviewed, tested and tweaked some variables naming and the logic.
> Add Magnetic Effect extension

- scripts/generate-extensions-registry.js
- scripts/types.d.ts
script tested, key is added only when available :+1:
> Add Author IDs to extension-registry

- Extensions/Checkpoints.json
- extensions-registry.json
Close https://github.com/GDevelopApp/GDevelop-extensions/issues/202
> Add the Checkpoints extension

- Extensions/CancellableDraggable.json
- Extensions/ThreeDFlip.json
Only typo fixes and version increment.
> [Flip, CancellableDraggable] Fix typos in comments.

- Extensions/MarchingSquares.json
* Add expressions to access the area borders (left, top, right and bottom)
* Add expressions to evaluate the normal vector for a given location
* Add actions to make hills on the field (with Gaussians)
* Add some long descriptions
* Add a link to a wiki page (there isn't much explanations on it yet)
* Fix some typos
This example uses it to do terraforming and apply forces to phisics balls.
* Project: https://www.dropbox.com/s/htn3nixly0pum77/marching-squares-terraforming.zip?dl=1
* Build: https://d8h.itch.io/marching-squares-terraforming
* Hills
```JavaScript
/**
* Merge a hill in the field.
* @param centerX {float} in scene basis
* @param centerY {float} in scene basis
* @param height {float} 
* @param radius {float} in scene basis
* @param opacity {float} 
* @param cappingRadiusRatio …
```
> [MarchingSquares] Add actions to make hills and evaluate the field normals.

- Extensions/ExtendedMath.json
I think this condition makes sense in this extension, but if not please suggest another.  :)
> Added condition "Is even"

- Extensions/DraggableSliderControl.json
Changes
* Handle cursor events according to object rotation, scale and position
* Fix the initial value when it's not 0
* Use color property type
* Define properties groups
* Define functions groups
* Add getters and setters for valueMin, valueMax and tickSpacing properties
* Change the extension and behavior description
* Fix 2 typos
Test project: https://www.dropbox.com/s/bf8i3ototgwvjqn/ShapePainterTransformationTest.zip?dl=1
> [Slider] Handle object transformations.

- .github/workflows/auto-pr.yml
- .github/workflows/build.yml
- .github/workflows/commands.yml
- .vscode/settings.json
- Make `!update` work when the file has been renamed
- Don't generate a PR until the extension passes automatic tests
- Add/Update issue output messages for increased clarity for the users of what's going on
Workflow deployed and tested on arthuro555/GDevelop-extensions, you can test it there.
> Various CI fixes

- Extensions/CameraZoom.json
This extension allows to zoom a camera on a layer at a given speed. The zoom speed is configurable and allows a constant or even variable zoom speed.
- Zoom by a factor every second
[Project.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8010761/Project.zip)
[Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8010762/Extension.zip)
See discussion history:
* https://github.com/GDevelopApp/GDevelop-extensions/issues/200
> New extension CameraZoom to zoom at a given speed.

- Extensions/ExtendedVariables.json
- This fix function name to respect the PascalCase for function name.
(So a lot of breaking change in functions)
- Add functions to copy a variables to another one, type and value(s) are copied.
> Update Extended variables extension

- Extensions/Swipe.json
Added tags and assigned the Input category in extension settings.
> Update tags for Swipe extension

- Extensions/CursorType.json
Changes:
- Variables names
- Add string list parameter for behavior
- Add Input group
- Fix Action
- Fix Behavior
Tested with an action and behavior on an object.
> [Fix] Cursor Type

- Extensions/DraggableSliderControl.json
Minor fix on parameters name and sign
> [Fix] Parameters of DraggableSlider

- Extensions/SmoothCamera.json
It was doing the same as the "follow on Y" action.
> [SmoothCamera] Fix the "follow on X" action.

- Extensions/DrawPathfinding.json
And some minor cleanup in logic.
https://liluo.io/games/93b0db63-5480-4ca5-8ed2-456a8458ef8c
[TestingPathfinding.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8559039/TestingPathfinding.zip)
> DrawPathfinding Update: Automatic creation of shape painter object and enforce absolute position

- Extensions/Noise.json
Project file:
[Testing-1D-Noise.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8548411/Testing-1D-Noise.zip)
> Added helper function for 1D noise (using 2D noise with a static value for one dimension)

- Extensions/MultitouchJoystick.json
Note: I decided to start a new PR with a clean branch from main. :)
- Removed the requirement for specific event ordering.
- Renamed "JoystickAmplitude" to "JoystickForce"
- Various small cleanups
https://liluo.io/instant-builds/2c8a3cc5-84f7-46b6-a3e8-b972ca9c2dc6
[MultitouchJoystick.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8670726/MultitouchJoystick.zip)
(I recently submitted this to the official example repo)
> Updates to Multitouch Joystick (take #2)

- Extensions/Gamepads.json
- Add "Any" to the parameters of the direction for the condition Stick pushed in a direction.
- Change wording to PascalCase for inputs name  (only cosmetic).
> Update gamepad extension 

- Extensions/DiscordRichPresence.json
Replaces the use of `getElectron().remote` with `getElectronRemote()`
> [DiscordRichPresence] Fix the extension for GD <v135

- Extensions/FireBullet.json
- Added the ability to shoot multiple bullets at once
- Cooldown: Time between shots (seconds)
- Bullet Quantity: Number of bullets shot at once
- Angle Variance: Each bullet angle will be randomized in this range (degrees)
- Firing Arc: Range of angles that bullets will shoot.  Bullets are evenly spread within this range.
- Changed "fire at position" to simply use "fire bullet" with a calculated angle
[Multiple Shot Fire Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8884844/Multiple.Shot.Fire.Extension.zip)
https://user-images.githubusercontent.com/8879811/173207256-9b4d0949-6b1b-41c6-9c13-5680d7fec16f.mp4
> Made FireBullet extension awesome!

- Extensions/FireBullet.json
> FireBullet: Change rotate bullet from a parameter to a property

- extensions/reviewed/MarchingSquares.json
- scripts/lib/ExtensionsValidatorExceptions.js
* The extension now use a library: https://github.com/D8H/scalar-field-painter
* The codes that change the behavior and the object are clearly identified
* The fill action now change the field the same way as other drawing tools
* https://github.com/GDevelopApp/GDevelop-examples/pull/337
* https://github.com/GDevelopApp/GDevelop-examples/pull/338
> [MarchingSquares] Refactor to extract a library

- extensions/reviewed/PinchGesture.json
This extension allows to:
* Move, rotate and/or zoom the camera according to pinch gestures
* Move, rotate and optionally scale objects according to pinch gestures
* Handle more specific needs with various expressions
* Project: https://www.dropbox.com/s/rcuboz3maw9eqb7/PinchExample.zip?dl=1
* Build: https://liluo.io/instant-builds/09b9ce7a-2a2a-48dd-9af6-3de4614f5720
There is some lines of JavaScript.
```JavaScrip
const x = eventsFunctionContext.getArgument("PositionX");
const y = eventsFunctionContext.getArgument("PositionY");
const layer = runtimeScene.getLayer(eventsFunctionContext.getArgument("Layer"));
eventsFunctionContext.returnValue = layer.convertInverseCoords(x, y)[0];
```
> [PinchGesture] Add an extension to move the camera or objects with pinching gestures.

- scripts/generate-extensions-registry.js
Build run and confirmed working
> Release community extensions

- extensions/community/VoiceRecognition.json
Added example links in the extension description
> Update Extension: Voice Recognition

- extensions/reviewed/BoidsMovement.json
Added example links in the extension description
> Update Extension: BoidsMovement

- extensions/reviewed/ValuesOfMultipleObjects.json
Size expressions:
- Width (min/max/average)
- Height (min/max/average)
https://liluo.io/victrisgames/valuesofmultipleobjects
[ValuesOfMultipleObjects.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9051264/ValuesOfMultipleObjects.zip)
https://user-images.githubusercontent.com/8879811/177462316-fb27a003-ac21-4fe6-94fa-8e4f2ba6647a.mp4
> ValuesOfMultipleObjects: Added size expressions

- extensions/community/ChatBubble.json
Added example links in the extension description
> Update Extension: Chat Bubble

- extensions/reviewed/Health.json
Thanks to @Mixen-me for this update!
> Health (update): Can now manage Max Health

- extensions/community/NewgroundsAPI.json
Added example links in the extension description
> Update Extension: Newgrounds API

- extensions/reviewed/DraggableSliderControl.json
Expressions:
- Length of track
- Thickness of track
- Height of thumb
Actions:
- Change opacity of halo when pressed
- Change opacity of halo when hovered
> Draggable Slider: Added expressions for more properties and some actions

- extensions/reviewed/SmoothCamera.json
Fixing a typo in parameter name (copy/paste error from X offset)
> SmoothCamera: Fix bug when setting Y offset with events

- extensions/reviewed/Choose.json
Array Tools also have functions to pick random array elements, but it's harder to find because of the name.
> [Choose a random value] add a link to Array Tools in the description

- extensions/community/PlatformLedgeGrabber.json
- scripts/lib/ExtensionsValidatorExceptions.js
* Grab platforms ledges within reach automatically.
More details on the PR for review:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/341
> New extension PlatformLedgeGrabber.

- scripts/generate-extensions-registry.js
> Put "General" as the default category in the registry

- extensions/reviewed/ExtendedVariables.json
Tested and approved:
https://forum.gdevelop.io/t/solved-extended-variables-bug/42390
> Extended Variables Support: Fix types in action parameters

- extensions/reviewed/BoidsMovement.json
> [Reviewed][Boids Movement] Use a more direct link to the example

- extensions/reviewed/RenderToSprite.json
Close https://github.com/GDevelopApp/GDevelop-extensions/issues/604
[Reviewed][RenderToSprite] Add a new action to render a scene area into a sprite (Thanks @VanCastar)
> [Reviewed][RenderToSprite] Add a new action to render a scene area into a sprite

- extensions/reviewed/MultitouchJoystick.json
Thanks to @jerikothomas!
https://github.com/GDevelopApp/GDevelop-extensions/issues/629
[Example_8way_TouchJoystick.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9792691/Example_8way_TouchJoystick.zip)
https://liluo.io/instant-builds/fdc4cde8-ae5b-4e7d-b410-16fd5bc9b1c8
> [Reviewed] [MultitouchJoystick] Added conditions for 8-way movement

- extensions/reviewed/URLTools.json
Resolves https://github.com/4ian/GDevelop/issues/4447
> Fix URLTools attr parameter reading

- extensions/reviewed/PanelSpriteButton.json
This GDevelop build is required to review this extension:
- https://www.dropbox.com/s/n9ovh2p3h5uhdfo/gdevelop-ebo-beta149-2022-10-31.7z?dl=1
- https://www.dropbox.com/s/gbd9bygacvl63dx/EventBasedObjectPrototypeDemo.zip?dl=1
> Panel sprite button

- extensions/reviewed/DrawPathfinding.json
The bug has almost no impact with the current path finding version but the next one will have longer path elements:
https://liluo.io/games/47f7973b-f3bc-4779-80be-d4baed26fef6?dev=true
It also changes some wording.
Example:
https://www.dropbox.com/s/tv5c0egzltxud69/PathfindingSmoothingTest.zip?dl=1
> [Reviewed] [DrawPathfinding] The first path element is now drawn.

- extensions/reviewed/Checkbox.json
- extensions/reviewed/DraggableSliderControl.json
Colors property private actions have an operator since GDevelop 5.1.150
> [Reviewed] [Checkbox] [Slider] Fix the actions to change colors for GDevelop 5.1.151

- extensions/reviewed/PanelSpriteButton.json
Also:
* Add a property for hovered fade out.
Demo project:
- https://github.com/GDevelopApp/GDevelop-examples/pull/404
Demo build:
- https://liluo.io/instant-builds/996f5bb5-2521-45fe-bd77-f39fc36d90d3
> [Reviewed] [Panel sprite button] handle multi-touch

- scripts/generate-extensions-registry.js
- scripts/lib/rules/FilledOutDescriptions.js
> Handle multi-line descriptions

- scripts/generate-extensions-registry.js
- scripts/lib/rules/DotsInSentences.js
- scripts/lib/rules/FilledOutDescriptions.js
Tested on the NavMesh extension.
> Flatten extensions description

- extensions/community/NavMeshPathfinding.json
> [Community] [NavMesh] Make description multi-line

- extensions/reviewed/RectangleMovement.json
Demo:
* https://github.com/GDevelopApp/GDevelop-examples/pull/415
> [Reviewed] [Rectangle movement] The initial position parameter is now taken into account

- extensions/reviewed/PixelPerfectMovement.json
Demo
- https://www.dropbox.com/s/zvgcxxaiyxouj7e/PixelPerfect_BUG.zip?dl=1
> [Reviewed] [Pixel perfect] Fix conflicts with the action to change the horizontal speed of platformer characters

- extensions/reviewed/Gamepads.json
> [Reviewed] [Gamepad] Fix typo in group name

- extensions/reviewed/Recolorizer.json
It keeps the scaleMode, wrapMode and alphaMode of the source PIXI.BaseTexture.
- https://github.com/GDevelopApp/GDevelop-examples/pull/416
> [Reviewed] [Recolorizer] Fix pixel art sprites blurring.

- extensions/reviewed/ColorConversion.json
Added expressions for calculating luminance of colors according to WCAG 2.0 standards.
> [Color conversion] Add expressions for calculating luminance.

- extensions/community/CurvedMovement.json
- scripts/lib/ExtensionsValidatorExceptions.js
* It allows to move objects on Bézier curve paths.
* Thanks @pampogokiraly
Following:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/535
- https://github.com/GDevelopApp/GDevelop-examples/pull/421
> [Community] [Curved movement] New extension

- extensions/reviewed/AnimationChanger.json
- extensions/reviewed/PlatformerCharacterAnimator.json
Change the animations and horizontal flipping of a platformer character based on their movement and interaction with platform objects.
How to use:
- At beginning of scene, use "Enable changing animations" or "Enable horizontal flipping" actions
- If you don't use the default animation names, change the animation names in the behavior properties
https://liluo.io/victrisgames/extension-animation-changer
~[AnimationChanger.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9483779/AnimationChanger.zip)~
[PlatformerCharacterAnimator.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10275302/PlatformerCharacterAnimator.zip)
https://user-images.githubusercontent.com/8879811/188296127-c17e90c8-ad4c-442f-b91d-67533647f537.mp4
> New extension: "PlatformerCharacterAnimator"

- extensions/community/PanelSpriteContinuousBar.json
- extensions/community/PanelSpriteSlider.json
- extensions/community/SpriteToggleSwitch.json
- extensions/community/TiledUnitsBar.json
> [Community] Add various custom objects for UI.

- extensions/reviewed/FireBullet.json
Test this change using the updated example game:
https://github.com/GDevelopApp/GDevelop-examples/pull/425
> [Fire Bullet] [Reviewed] Update: Added the ability to specify the layer that bullets are created on

- extensions/reviewed/TimeFormatter.json
[TimeFormatter] Added an expression for HH:MM:SS.000 (displays milliseconds)
> [TimeFormatter] Added an expression for HH:MM:SS.000 (displays milliseconds)

- extensions/reviewed/FireBullet.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/434
> [Reviewed] [Fire bullet] Fix bullet angle was the firing angle without the variance.

- extensions/reviewed/PanelSpriteButton.json
This doesn't change anything outside of the extension events being simpler.
- https://github.com/GDevelopApp/GDevelop-examples/pull/438
> [Reviewed] [Button] Use the new touch conditions introduced in GDevelop 5.1.156

- extensions/community/PanelSpriteSlider.json
- extensions/community/SpriteToggleSwitch.json
> [Community] [Slider and Toggle Switch] Upgrade the ButtonFSM behavior

- extensions/reviewed/Record.json
It doesn't change anything.
It's just to make the review easier.
> [Reviewed] [Record] No change: multi-lined JavaScript events

- extensions/reviewed/SpriteMultitouchJoystick.json
* The name can no longer be a custom value.
- https://github.com/GDevelopApp/GDevelop-examples/pull/440
> [Reviewed] [Multitouch joystick] Add choices for the joystick name.

- extensions/reviewed/MouseHelper.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/450
> [Reviewed] [Cursor object] Remove the button behavior

- extensions/reviewed/YSort.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/460
> [Reviewed] [Y-Sort] Fix a 1-frame delay.

- extensions/reviewed/FireBullet.json
- Bullet speed variance: Each bullet speed will be adjusted by a random value within this range (pixels/second)
https://liluo.io/victrisgames/extension-fire-bullet
https://github.com/GDevelopApp/GDevelop-examples/pull/466
https://user-images.githubusercontent.com/8879811/217987952-f81ba781-3cdb-4857-a780-304cd7a7a378.mp4
> [FireBullet] [Reviewed] Added bullet speed variance (useful for shotgun effect)

- extensions/community/DynamicWater.json
@Alios5 let me know if you want any additional changes to your extension.
I would love to get a short list of the changes if you can provide it.
> [Community] [Dynamic water] Fixes bug when multiple water objects are used. Thanks @Alios5!

- extensions/reviewed/PanelSpriteSlider.json
> [Slider] Fix a shifting when the slider is rotated

- extensions/community/NavMeshPathfinding.json
* Add a behavior to change the animation according to the movement direction
- https://github.com/GDevelopApp/GDevelop-examples/pull/484
> [NavMesh path finding] Fix obstacle deletion handling.

- .github/workflows/auto-pr.yml
The bot was incorrectly displaying errors one at a time instead of showing all the issues at once. This should fix it.
> Fix bot error display

- .github/workflows/auto-pr.yml
The bot sliced the last character away instead of the first new line 🤦‍♂️
> Fix the bot's slicing

- extensions/reviewed/AdvancedJump.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/492
> [Advanced jump] Declare units of measurement

- extensions/reviewed/LinearMovement.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/491
> [Linear movement] Declare units of measurement

- extensions/reviewed/StayOnScreen.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/491
> [Stay on screen] Declare units of measurement

- extensions/reviewed/Flash.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/491
> [Flash] Declare units of measurement

- extensions/reviewed/RectangleMovement.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/490
> [Rectangle movement] Declare units of measurement

- extensions/reviewed/SmoothCamera.json
- Declare units of measurement
- Add an operator to the actions to change the camera offset
- https://github.com/GDevelopApp/GDevelop-examples/pull/490
> [Smooth camera] Declare units of measurement

- extensions/reviewed/Health.json
- Declare units of measurement
- Add conditions for expressions
- Add operators to some actions
- https://github.com/GDevelopApp/GDevelop-examples/pull/491
> [Health] Declare units of measurement

- extensions/reviewed/FireBullet.json
- `IsReadyToShoot` now returns true when "has just fired" is true.
https://github.com/GDevelopApp/GDevelop-examples/pull/497
> [Reviewed] [Fire bullet] Allow to fire from several locations at once

- extensions/reviewed/FireBullet.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/497
> [Reviewed] [Fire bullet] Forbid to fire while deactivated

- extensions/reviewed/DraggablePhysics.json
See example PR for playable game: https://github.com/GDevelopApp/GDevelop-examples/pull/494
> [Draggable Physics] [Reviewed] Updated extension with getters, setters, and units

- extensions/reviewed/Checkpoints.json
- Use identifiers to have autocompletion for checkpoint names
- Remove the help page broken link
- Add a link to the platformer example in the description
- Rewrite the description
- https://github.com/GDevelopApp/GDevelop-examples/pull/505
> [Checkpoints] Add checkpoint name autocompletion

- extensions/reviewed/MousePointerLock.json
> [Reviewed] [Mouse pointer lock] Update the example link

- extensions/reviewed/Checkpoints.json
- extensions/reviewed/MousePointerLock.json
> Fix a typo in descriptions

- extensions/reviewed/OrbitingObjects.json
See https://github.com/GDevelopApp/GDevelop-examples/pull/489 for example game.
> [Reviewed] [OrbitingObjects] Add elliptical orbit function that simulates 3D by changing Z-order

- extensions/reviewed/Bounce.json
- extensions/reviewed/ScreenWrap.json
- extensions/reviewed/StayOnScreen.json
> Add some example links

- extensions/reviewed/DraggablePhysics.json
- extensions/reviewed/DungeonGenerator.json
- extensions/reviewed/OrbitingObjects.json
> Add more example links

- extensions/reviewed/AdvancedProjectile.json
- Control how a projectile object moves including speed, acceleration, distance, and lifetime.
https://gd.games/victrisgames/extension-advanced-projectile
https://user-images.githubusercontent.com/8879811/229410580-9b90add5-2602-46f7-989b-63f16fa57a32.mp4
See the example game PR:
https://github.com/GDevelopApp/GDevelop-examples/pull/506
> [Reviewed] [AdvancedProjectile] Add "AdvancedProjectile" extension

- extensions/community/CurvedMovement.json
> [Curved movement] Handle the exponential notation for numbers in SVG paths

- extensions/reviewed/Inventories.json
It has the same features of the one integrated to GDevelop but it's written with events so users can modify it if they need to.
It requires:
- https://github.com/4ian/GDevelop/pull/5220
- https://github.com/GDevelopApp/GDevelop-examples/pull/500
> [Reviewed] [Inventories] A rewrite of the extension with events

- extensions/reviewed/FirstPersonCamera.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/529
> [Reviewed] [First person camera] Move the camera to look though objects eyes

- extensions/reviewed/SpriteMultitouchJoystick.json
- Add `StickForceX` and `StickForceY` expressions
- `JoystickAngle` is renamed `StickAngle`
- `JoystickForce` is renamed `StickForce`
- https://github.com/GDevelopApp/GDevelop-examples/pull/529
> [Reviewed] [Multitouch joystick] Add expressions StickX and StickY

- extensions/reviewed/Billboard.json
- scripts/lib/ExtensionsValidatorExceptions.js
* https://github.com/GDevelopApp/GDevelop-examples/pull/524
> [Reviewed] [Billboard] Rotate 3D objects to appear like 2D sprites

- extensions/reviewed/ThirdPersonCamera.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/531
> [Reviewed] [Third person camera] Move the camera  to look at an object from a given distance

- extensions/reviewed/SpriteMultitouchJoystick.json
> [Reviewed] [Multitouch joystick] Replace deprecated expression calls

- extensions/reviewed/FireBullet.json
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/889ba0cd-d7ad-470d-9786-30bc2561d059
https://twitter.com/VictrisGames/status/1659755966789984257
> [Fire Bullet] [Reviewed] Added action to "fire bullet at an object"

- .github/workflows/auto-pr.yml
- .github/workflows/build.yml
- .github/workflows/commands.yml
1. Bumps [actions/checkout](https://github.com/actions/checkout) from v2 to v3
2. Bumps [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) from v4 to v5
3. Bumps [xt0rted/pull-request-comment-branch](https://github.com/xt0rted/pull-request-comment-branch) from v1 to v2
> Update GitHub Action

- extensions/reviewed/RectangleMovement.json
- Add functions to move around the border of another object (makes designing levels more visual)
- Add condition for clockwise property
> [Rectangle Movement]  [Reviewed] Update: Add ability to move around the border of another object

- extensions/reviewed/Share.json
- scripts/lib/ExtensionsValidatorExceptions.js
Based on https://forum.gdevelop.io/t/solved-share-button-in-gdevelop/37395, heavily reworked to avoid variable usage, have a few conditions/expressions and use an async action :)
> Add Share extension

- extensions/reviewed/ObjectStack.json
- Add an action to check an object at an exact height
- Add an action to insert the content of a stack into another stack
- Add an operator to the stack height condition
- https://github.com/GDevelopApp/GDevelop-examples/pull/540
> [Reviewed] [Object stack] Add quality of life features

- extensions/community/CurvedMovement.json
* Add an action to duplicate a path.
- https://github.com/GDevelopApp/GDevelop-examples/pull/545
> [Community] [Curved movement] Fix the action to append paths

- extensions/community/RectangularMovement.json
- extensions/community/SineMovement.json
> [Community] Add a deprecated suffix to some behaviors

- extensions/reviewed/RectangleMovement.json
https://gd.games/victrisgames/rectangle-movement-positions
[Rectangle Movement Positions.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12268653/Rectangle.Movement.Positions.zip)
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/e419143f-b4b0-4b81-8166-bbb80f091b4a
> [Rectangle Movement] Update: Add option to select the position on the border (inside, center, outside)

- extensions/reviewed/ObjectSlicer.json
Fixes: https://github.com/GDevelopApp/GDevelop-extensions/issues/950
> [Object Slicer] [Reviewed] [Update] Fix bug in parameter name for condition to delete object

- extensions/reviewed/Flash.json
> [Flash] [Reviewed] Removed deprecated lifecycle function

- extensions/reviewed/ScreenWrap.json
> [Screen wrap] [Reviewed] Fix physics version that had copy/paste errors from non-physics version

- extensions/reviewed/AdvancedHTTP.json
- scripts/lib/ExtensionsValidatorExceptions.js
An advanced HTTP client with supports for headers, cache control, built-in opt-in CORS proxy (hosted on the edge via Cloudflare Workers).
Everything has been thoroughly tested via a mock server.
All events can be seen in this example screenshot:
> [Reviewed] Add AdvancedHTTP extension

- extensions/community/Tween3D.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/559
- https://gd.games/d8h/test-stretch
- https://github.com/GDevelopApp/GDevelop-examples/pull/568
> [Community] [3D tween] Smoothly animate scale and rotation of 3d models

- extensions/reviewed/PlatformerCharacterAnimator.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/562
> [Reviewed] [Platformer character animator] Handle 3D models

- extensions/reviewed/CurvedMovement.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/545
> [Reviewed] [Curved movement] Add a condition to check the number of loop

- extensions/reviewed/ShakeObject3D.json
* Allow the shake to start automatically.
- https://github.com/GDevelopApp/GDevelop-examples/pull/568
> [Reviewed] [3D object shake] Unify the behaviors for 3D models and 3D boxes

- extensions/reviewed/FaceForward.json
The face forward extension is excellent but sometimes fails to get the default direction, adding a default direction property fixes the issue.
> Update face forward extension

- extensions/community/WithThreeJS.json
> [Community] [WithThreeJs] version 1.0.0

- extensions/reviewed/ArrayTools.json
- scripts/lib/ExtensionsValidatorExceptions.js
A long overdue overhaul of the array tools extension!
- Use Scene Variable parameters instead of string parameters (allows using nested arrays)
- Add Global and Object variable variants
- Change the icon to a "list" icon, rather than a `[ ]` icon, for clarity
- Rename some expressions to fit best practices
- Clean up the code a lot, replaced abbreviations with good and consistent variable names
- Add categories to be able to navigate the different functions more easily
This goes without saying, but this is a breaking change!
> Array tools v2

- extensions/reviewed/ObjectSpawner.json
https://gd.games/victrisgames/cats-vs-aliens
https://github.com/GDevelopApp/GDevelop-examples/pull/573
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/416bbab3-edfd-4bc9-8b89-3682917a6636
> [Object Spawner] [Reviewed] Updated to include a property for capacity

- extensions/reviewed/ValuesOfMultipleObjects.json
[PickHighestLowestValue.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12679984/PickHighestLowestValue.zip)
https://github.com/GDevelopApp/GDevelop-extensions/assets/8879811/9b64d690-da4b-41eb-bf26-b6e098f917c6
> [Reviewed] [Values of multiple objects] Updated to include min/max z-order (Thanks Uiles!)

- .github/workflows/auto-pr.yml
- __tests__/auto-pr/auto-pr.spec.js
- scripts/check-single-extension.js
Fix an error introduced into the extension submission pipeline update made a few hours ago 🤦‍♂️
> Fix auto-pr system

- .github/workflows/auto-pr.yml
- .github/workflows/commands.yml
1. Fixed the issue where error comments occur when a comment is posted during the upload of a zip file. (It seems that the action will again trigger when the upload is complete.) ([problem ran action](https://github.com/GDevelopApp/GDevelop-extensions/actions/runs/5536079994/jobs/10103262105))
<details>
<summary> Run info </summary>
```bash
curl -L $(echo $BODY | grep -ioEh 'https?://\S+.zip' -m1) -o /tmp/ext.zip
unzip -o /tmp/ext.zip -d ./extensions/community
shell: /usr/bin/bash -e {0}
env:
BODY: I've made the requested fixes and uploaded the updated extension file. Please review the file and make sure that it contains the changes you expect.
!update
[Uploading CountdownTimer.json.zip…]()
```
</details>
2. Added a clearer error comment for when there are no changes in Git.
3. Fix small …
> Improve Automatic PR Creation GitHub Action and Command GitHub Action.

- extensions/community/WithThreeJS.json
Supports GDevelop v5.2.173 and PixiJS v7.3.0.
> [Community] [WithThreeJs] version 1.0.1

- extensions/reviewed/ThirdPersonCamera.json
It also better handles extreme elevation angles.
- https://github.com/GDevelopApp/GDevelop-examples/pull/575
> [Reviewed] [Third person camera] Use object Z position

- extensions/community/Raycaster3D.json
- scripts/lib/ExtensionsValidatorExceptions.js
- https://github.com/GDevelopApp/GDevelop-examples/pull/582
> [Community] [3D raycaster] Find 3D objects that cross a line

- extensions/community/Tween3D.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/583
> [Community] [3D Tween] Tweens can now also be applied to boxes

- extensions/community/ParticleEmitter3D.json
Fixes https://github.com/GDevelopApp/GDevelop-extensions/issues/1019
- https://github.com/GDevelopApp/GDevelop-examples/pull/585
- https://github.com/GDevelopApp/GDevelop-examples/pull/582
> [Community] [3D particles] Fix wrong position of the 1st particle

- extensions/community/WithThreeJS.json
Supports GDevelop v5.3.180
Added custom object to always enable built-in 3D rendering.
> [Community] [WithThreeJs] Supports GDevelop v5.3.180

- extensions/community/CrazyGamesAdApi.json
- scripts/lib/ExtensionsValidatorExceptions.js
- [TestCrazyGameExtension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/13451653/TestCrazyGameExtension.zip)
> [CrazyGames] Upgrade to 2.x of CrazyGames SDK

- extensions/reviewed/Flash.json
- Changed an input parameter to type "effect"
- Minor wording changes
https://github.com/GDevelopApp/GDevelop-examples/pull/603
> [Reviewed] [Flash object] Added get/set functions for half-time property

- extensions/community/WithThreeJS.json
Added 3D Group object.
Added 3D object variable function.
Improved Bounding Box Collision.
> [Community] [WithThreeJs] Added new features.

- extensions/community/WithThreeJS.json
Added Lerp function and improved Raycast function.
> [Community] [WithThreeJs] Improved Raycast features.

- scripts/lib/ExtensionsValidatorExceptions.js
This needs to be merged before merging #1069.
> Add exception for SupabaseSaveState to ExtensionsValidatorExceptions.js

- extensions/community/Collision3D.json
- scripts/lib/ExtensionsValidatorExceptions.js
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1048
- https://editor.gdevelop.io/?project=https://raw.githubusercontent.com/D8H/GDevelop-examples/3rd-person/examples/3d-third-person/3d-third-person.json
> [3D collision] Check collision and distance between 3D objects

- extensions/community/TopDownWalk.json
- extensions/community/Walk3D.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/622
> [Community] [3D walk] Turn and move objects forward and sideway

- extensions/community/FlexBox.json
Following
- https://forum.gdevelop.io/t/issue-with-scenes-changes/54668/31
> [FlexBox] Downgrade FlexBox to community tier because of a memory leak

- extensions/community/TopDownCornerSliding.json
- extensions/community/Tween3D.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/627
> [3D Tween] Deprecate tween actions that are now in the built-in Tween behavior

- extensions/reviewed/ThirdPersonCamera.json
- https://editor.gdevelop.io/?project=https://raw.githubusercontent.com/D8H/GDevelop-examples/3rd-person/examples/3d-third-person/3d-third-person.json
> [Third person camera] Add a smooth camera behavior

- extensions/reviewed/AutoTyping.json
> [Reviewed] [Autotyping] Simplify the description

- extensions/reviewed/ShakeObject3D.json
- Add a condition to check if the shaking is stopping
- Fix a crash when the "Start to shake at the object creation" property is enabled from the 1st scene
- Fix description typo
- Use the new syntax to access properties and parameters
- Use ES6 syntax for classes
- https://github.com/GDevelopApp/GDevelop-examples/pull/631
> [3D object shake] Fix description typo and use the new syntax

- extensions/community/CountdownTimer.json
> [Community] [Countdown timer] Fix a typo in the restart action name

- extensions/community/CameraShake3D.json
- scripts/lib/ExtensionsValidatorExceptions.js
- https://github.com/GDevelopApp/GDevelop-examples/pull/637
> [Community] [3D camera shake] Shake layer cameras on 3 rotations

- extensions/reviewed/Parallax.json
- The object can be in a layer that moves.
- https://github.com/GDevelopApp/GDevelop-examples/pull/638
> [Reviewed] [Parallax] Make the parallax start with an offset of 0

- extensions/reviewed/Parallax.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/638
> [Reviewed] [Parallax] Fix a shift when zooming

- extensions/reviewed/Sticker.json
- [TestStickerAndPanel.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/14715783/TestStickerAndPanel.zip)
> [Reviewed] [Sticker] Fix object positions after a size change when angle is 0

- extensions/reviewed/FireBullet.json
- Add new expression: "Time before reload finishes"
- Prevent negative values for ammo
- Adjust firing arc for 360 degrees to prevent two bullets from using the same angle
> [Reviewed] [Fire Bullet] Minor updates and fixes (version 0.7.0)

- extensions/reviewed/TiledUnitsBar.json
Fixes:
- https://forum.gdevelop.io/t/bug-suspicion-resource-bar-object-separated-units/54832
> [Reviewed] [Resource bar (separated units)] Fix max value action

- extensions/reviewed/ThreeDFlip.json
Tested:
- on the "Pair" example:
- https://github.com/GDevelopApp/GDevelop-examples/pull/643
- and the example from a previous version:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/224
> [Reviewed] [3D flip] Allow to use animations to flip sprites

- extensions/reviewed/CameraShake.json
The game feel example from this PR:
- https://github.com/GDevelopApp/GDevelop-examples/pull/643
> [Reviewed] [Camera shake] Use extension variables

- extensions/community/WithThreeJS.json
Support for multiplayer behaviors and many other improvements.
> [Community] [WithThreeJs] Support multiplayer behavior

- extensions/reviewed/PhysicsCar.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/677
> [Reviewed] [Physics car] Simulate car motion with the Physics 2 behavior

- extensions/reviewed/AutoTyping.json
- The 3 behaviors has been merged into a unique one.
- Use properties instead of variables.
- Simplify the events.
> [Reviewed] [Autotyping] Unify the 3 behaviors

- extensions/reviewed/FireBullet.json
- Use the new syntax
- Remove some unused variables
> [Reviewed] [Fire bullet] Fix variance in multi-shots being used twice

- extensions/reviewed/LinearMovement.json
Following:
- https://github.com/GDevelopApp/GDevelop-extensions/issues/1359
- https://github.com/GDevelopApp/GDevelop-examples/pull/687
> [Linear movement] Add a behavior to move objects ahead according to their angle

- extensions/reviewed/RollingCounter.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/697
> [Reviewed] [Rolling counter] Smoothly change a counter value in a text object

- extensions/community/WithThreeJS.json
- Added "Check 3D Object Is Within 3D Camera FOV" condition.
- Added "Change 3D Object Raycast Detection" action.
> [Community] [WithThreeJs] Added drawing detection and improved raycasting.

- scripts/lib/ExtensionsValidatorExceptions.js
> Update ExtensionsValidatorExceptions.js to include Supabase

- extensions/reviewed/FlashTransitionPainter.json
Following:
- https://github.com/GDevelopApp/GDevelop-extensions/issues/1437
- https://github.com/GDevelopApp/GDevelop-examples/pull/728
> [Reviewed] [Flash and transition] Fix the opacity

- scripts/lib/ExtensionsValidatorExceptions.js
> Added _wortalExtension to gdjs for WortalSDK

- extensions/reviewed/SpriteMultitouchJoystick.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/747
> [Reviewed] [Multi-touch joystick] Allow to use the joystick from anywhere on the screen

- extensions/reviewed/SpriteMultitouchJoystick.json
- scripts/lib/ExtensionsValidatorExceptions.js
- https://github.com/GDevelopApp/GDevelop-examples/pull/748
> [Reviewed] [Multi-touch joystick] Simplify joystick teleportation

- extensions/reviewed/MousePointerLock.json
- scripts/lib/ExtensionsValidatorExceptions.js
- https://github.com/GDevelopApp/GDevelop-examples/pull/748
> [Reviewed] [Pointer lock] Allow multi-touch devices to use the pointer lock

- extensions/reviewed/PlayerAvatar.json
- scripts/lib/ExtensionsValidatorExceptions.js
The players need to change their picture by themself on Gravatar, soon the avatar will be editable on their GDevelop profile.
> [Reviewed] [Player Avatar] Add a new custom object for the profile picture from GDevelop accounts

- extensions/reviewed/PlayerAvatar.json
> Add required version  >=5.5.222 for the player avatar extension

- extensions/community/HedgehogPlatformer.json
- extensions/community/ScreenOrientationChecker.json
- extensions/reviewed/CopyCameraSettings.json
- extensions/reviewed/EllipseMovement.json
- extensions/reviewed/Gamepads.json
- extensions/reviewed/SmoothCamera.json
- extensions/reviewed/SpriteMultitouchJoystick.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/765
> Migrate some extensions to properties as variables

- extensions/reviewed/PlaygamaBridge.json
> Update extension: PlaygamaBridge v1.20.1 

- extensions/reviewed/CrazyGamesAdApi.json
Close https://github.com/GDevelopApp/GDevelop-extensions/issues/1552
Update [CrazyGames SDK to V3](https://docs.crazygames.com/sdk/) (Thanks @planktonfun!)
Here is the updated example with the updated extension, that is working on their [QA Tool](https://developer.crazygames.com/games):
The example: [R4-CrazyGamesApiV3.zip](https://github.com/user-attachments/files/18991083/R4-CrazyGamesApiV3.zip)
The GDevelop updated documentation: https://github.com/GDevelopApp/GDevelop-documentation/pull/268
Once both are approved I'll merge the example with a thumbnail.
> Update CrazyGames SDK to V3

- extensions/reviewed/BehaviorRemapper.json
- extensions/reviewed/PhysicsCharacter3DKeyMapper.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/772
> Use keyboard key properties in several extensions

- extensions/community/HedgehogPlatformer.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/773
> [Community] [Hedgehog platformer] Add a condition for the spin-dash start

- extensions/reviewed/SmoothCamera.json
- https://github.com/GDevelopApp/GDevelop-examples/pull/773
> [Reviewed] [Smooth camera] Fix the camera delay setter

- .github/workflows/auto-pr.yml
- __tests__/auto-pr/auto-pr.spec.js
- __tests__/auto-pr/test-extensions/community/Fake.json
- __tests__/auto-pr/test-extensions/reviewed/ArrayTools.json
- scripts/check-single-extension.js
- scripts/extract-extension.js
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1034
- Revert the reviewed extension submission part.
> Improve extension submission process

- extensions/community/WithThreeJS.json
Added "💡Change 3D Light Color" action.
Added "💡Change 3D Light Intensity" action.
Added "💡Change 3D Ambient Light Color" action.
Added "🏞️Change 3D Background Color" action.
> [Community] [WithThreeJs] Added a function to gradually change the light color.

- extensions/community/TopDownMovementAnimator.json
Also allow to use animations without direction suffix
> [Community] [Top-down animator] Allow to disable animation pause

- extensions/reviewed/Gamepads.json
- extensions/reviewed/PhysicsCar3DKeyMapper.json
- extensions/reviewed/SpriteMultitouchJoystick.json
It needs
- https://github.com/4ian/GDevelop/pull/7479
> [Reviewed] Add input mapping behaviors for the 3D physics car

- extensions/community/HedgehogPlatformer.json
Regression from
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1699
> [Community] [Hedgehog platformer] Fix the animator behavior

- extensions/reviewed/SmoothCamera.json
- Rightward maximum speed
- Follow free area left border
- Follow free area right border
> [Reviewed] [Smooth camera] Fix some actions to change the properties

- extensions/reviewed/Sticker.json
Fixes https://github.com/GDevelopApp/GDevelop-extensions/issues/1759
> [Reviewed] [Sticker] Fix a memory leak

- extensions/reviewed/PanelSpriteButton.json
Needs
- https://github.com/4ian/GDevelop/pull/7755
> [Reviewed] [Button] Allow to use bitmap text for the label

- extensions/community/Scrollbar.json
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1824
> [Community] [Scrollbar] A scrollbar to help making a scroll view

- extensions/community/A3F.json
- Fixed bugs in "👀 Look at position" and "👀 Look at 3D object" actions
- Corrected parameter name in "↔️ Check the distance between two objects in 3D"
- Improved wording in "😀 Change morph target value" description
> [Community] [Advanced 3D Features] Fix look-at bugs and minor issues

- extensions/community/ScreenOrientationChecker.json
- The color can be set on the shape painter directly from the variant editor
> [Community] [Screen orientation checker] Remove the background color property
